### ISSUE TITLE
feat: [공통 컴포넌트] 평가 진행률 컴포넌트 구현

### ISSUE THREAD

**Issue by vangona** [KPT-Final-Team9/front#50]
## 🧐 어떤 기능을 구현하나요?
![image](https://github.com/KPT-Final-Team9/front/assets/69471032/f8e4b968-07b6-4485-af42-0b1b3b5959b3)

## ✅ 작업 상세 내용
- [ ]  내용
- [ ]  내용

**Comment by Lamyzm** [comment]
따로 구현해서 닫겠습니다
